Repository FabrizioR17/SU7G3, pull requests merged in 2023-01, with the labels that each got.

#1 agregando los modelos , user , song , playlist y la ruta /
  dist/index.js
  index.ts
  package.json
  prisma/dev.db
  prisma/dev.db-journal
  prisma/migrations/20230124122630_init/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
Labels: modelos-ruta/

#2 get post users
  index.ts
Labels: enhancement

#3 agregando ruta get y post de songs
  index.ts
  prisma/dev.db
  prisma/dev.db-journal
  prisma/migrations/20230124142740_cambio_privacysong/migration.sql
  prisma/schema.prisma
Labels: post-get-songs

#4 get songs by id + post playlist
  index.ts
Labels: enhancement

#6 login
  index.ts
Labels: enhancement
